services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mic8475
      MYSQL_DATABASE: test
      MYSQL_USER: admin
      MYSQL_PASSWORD: mic8475
    volumes:
      - ./master_db/data:/var/lib/mysql  	  
#redis
  redis:
    image: redis:7.2.4
    container_name: myRedis_container
    restart: always
    ports:
      - "6379:6379"
#zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: myZookeeper_container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ./zookeeper-data:/var/lib/zookeeper/data
#Kafka
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: myKafka_container
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CREATE_TOPICS: "customer:1:1"
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    
